// <auto-generated />
namespace reFactorPrj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 資料庫異動 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(資料庫異動));
        
        string IMigrationMetadata.Id
        {
            get { return "202102260250583_資料庫異動"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
