// <auto-generated />
namespace reFactorPrj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 調整單位 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(調整單位));
        
        string IMigrationMetadata.Id
        {
            get { return "202103030518046_調整單位"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
