// <auto-generated />
namespace reFactorPrj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class 修改tRecipes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(修改tRecipes));
        
        string IMigrationMetadata.Id
        {
            get { return "202103020317177_修改tRecipes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
